import type { RoomInput } from '../types/room';

const defaultDestination = { latitude: -23.535, longitude: -46.573 };

export const initialRooms: RoomInput[] = [
  {
    code: 'F101',
    name: 'Laboratório de Informática V',
    buildingId: 'F',
    floor: 1,
    description: 'Laboratório de Informática V, Bloco F.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'F102',
    name: 'Sala F102',
    buildingId: 'F',
    floor: 1,
    description: 'Sala de aula do Bloco F.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'RECEPÇÃO',
    name: 'Recepção',
    buildingId: 'A',
    floor: 0,
    description: 'Recepção do campus.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'BIBLIOTECA',
    name: 'Biblioteca',
    buildingId: 'A',
    floor: 0,
    description: 'Biblioteca do campus.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'CONSULTORIO-SAUDE',
    name: 'Consultório de Saúde',
    buildingId: 'A',
    floor: 0,
    description: 'Consultório de saúde do campus.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'COORD-CURSOS',
    name: 'Coordenação de Cursos e Gestão do Campus',
    buildingId: 'A',
    floor: 0,
    description: 'Coordenação de cursos e gestão do campus.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'NPJ',
    name: 'NPJ',
    buildingId: 'A',
    floor: 0,
    description: 'Núcleo de Práticas Jurídicas - Escritório de Assistência Jurídica Dr. Arnaldo Vasconcelos.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'NAE',
    name: 'NAE',
    buildingId: 'A',
    floor: 0,
    description: 'Núcleo de Apoio ao Estudante.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'NAAP',
    name: 'NAAP',
    buildingId: 'A',
    floor: 0,
    description: 'Núcleo de Apoio e Acompanhamento Pedagógico.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'SALA-PROFESSORES',
    name: 'Sala de Professores',
    buildingId: 'A',
    floor: 0,
    description: 'Sala reservada aos professores.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'DIRECAO',
    name: 'Direção',
    buildingId: 'A',
    floor: 0,
    description: 'Direção do campus.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'NAF-PROJETE',
    name: 'NAF-Projete',
    buildingId: 'A',
    floor: 0,
    description: 'Núcleo de apoio e atendimento NAF-Projete.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'SEP',
    name: 'SEP',
    buildingId: 'A',
    floor: 0,
    description: 'Serviço de apoio estudantil.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'SECRETARIA-ALUNOS',
    name: 'Secretaria de Alunos',
    buildingId: 'A',
    floor: 0,
    description: 'Atendimento da secretaria de alunos.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'POLO-EAD',
    name: 'Polo EAD',
    buildingId: 'A',
    floor: 0,
    description: 'Atendimento do Polo EAD.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'WC',
    name: 'WC',
    buildingId: 'A',
    floor: 0,
    description: 'Banheiro.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'WC-FAMILIA',
    name: 'WC Família',
    buildingId: 'A',
    floor: 0,
    description: 'Banheiro família.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'HUB',
    name: 'HUB',
    buildingId: 'A',
    floor: 0,
    description: 'Área de convivência e orientação.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'SALA-MATRICULA',
    name: 'Sala de Matrícula',
    buildingId: 'A',
    floor: 0,
    description: 'Atendimento para matrícula e inscrição.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'REFEITORIO',
    name: 'Refeitório',
    buildingId: 'D',
    floor: 0,
    description: 'Refeitório do Bloco D.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'BACK-OFFICE',
    name: 'Back Office',
    buildingId: 'D',
    floor: 0,
    description: 'Back office do Bloco D.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
  {
    code: 'LAB-LEPE-LPSS',
    name: 'Lab. Informática (LEPE/LPSS)',
    buildingId: 'D',
    floor: 0,
    description: 'Laboratório de informática do LEPE/LPSS, Bloco D.',
    destination: defaultDestination,
    routeId: null,
    active: true,
  },
];
